name: CI

on: [push]

env:
  WEB_IMAGE: docker.pkg.github.com/${{ github.repository }}/web
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check-out a repo
        uses: actions/checkout@v2

      - name: Docker
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          docker pull $WEB_IMAGE:latest || true
          docker-compose up
          docker push $WEB_IMAGE:latest
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/deploy'
    steps:
      - uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.REMOTE_KEY }}
      - name: Deploy on remote
        env:
          DOCKER_HOST: ${{ secrets.REMOTE_HOST }}
        run: |
          docker pull $WEB_IMAGE:latest
          docker-compose down -f docker-compose.prod.yml || true
          docker-compose up -d --build -f docker-compose.prod.yml

